/**
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/15/2016
 */
var configuration = require('../lib/configuration');

var testConfiguration = {
    ASSERT_PRECISION: 0.01,
    TEST_TIMEOUT: 30000
};

module.exports = testConfiguration;
